version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: task_management_db
    environment:
      POSTGRES_DB: task_management_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  rabbitmq:
    image: "rabbitmq:3.12.8-management"
    container_name: "rabbitmq-container"
    ports:
      - "5672:5672"
      - "15672:15672"

  app1:
    image: "task-management:latest"
    container_name: "task-app-1"
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - rabbitmq

  app2:
    image: "task-management:latest"
    container_name: "task-app-2"
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq